add_newline = false
# Move all information on right prompt
format = """$character"""
right_format = """$all"""

[line_break]
disabled = true

[character]
success_symbol = "[â¯](white)[â¯](green)[â¯](bold green)"
error_symbol = "[â¯](white)[â¯](red)[â¯](bold red)"
vicmd_symbol = "[â®](white)[â®](blue)[â®](bold blue)"

[cmd_duration]
min_time = 1000
format = "*[$duration](bold yellow)*"

# Somehow cloud â›… emoji breaks prompt so excludes cloud related prompts
[aws]
disabled = true
[gcloud]
disabled = true

[git_branch]
style = "bold blue"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold green"
format = '([$all_status $ahead_behind]($style))'

conflicted = "ğŸ³"
ahead = "â¡"
behind = "â¬…"
diverged = "ğŸ˜µ"
up_to_date = ""

untracked = "ğŸ‘€"
stashed = ""
modified = "[*](bold red)"
staged = '[++\($count\)](green)'
renamed = "[*](bold red)"
deleted = "[*](bold red)"

[python]
format = '[${symbol}${pyenv_prefix}(\($virtualenv\) )]($style)'

[nodejs]
disabled = true
