add_newline = false

[aws]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
style = "bold green"
format = '([$all_status $ahead_behind]($style) )'

conflicted = "ğŸ³"
ahead = "â¡"
behind = "â¬…"
diverged = "ğŸ˜µ"
up_to_date = ""

untracked = "ğŸ‘€"
stashed = "ğŸ“¦"
modified = "âŒ"
staged = '[++\($count\)](green)'
renamed = "âŒ"
deleted = "âŒ"

[python]
format = '[${symbol}${pyenv_prefix}(\($virtualenv\) )]($style)'
